name: Docker Build, Publish and Deploy

on:
  push:
    branches: [master]


jobs:
  docker_build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Define docker image tag
        run: |
          echo "DOCKER_IMAGE_TAG=$(git describe --tags)" >> $GITHUB_ENV
          echo $DOCKER_IMAGE_TAG

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with: 
          context: .
          platforms: 'linux/amd64'
          push: true
          tags: tolulopeayo/ci-test:${{ env.DOCKER_IMAGE_TAG }}

  deploy_to_dev:
    permissions: 
      id-token: write
      contents: write
    needs: [docker_build_and_publish]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Repository Dispatch Dev
        env:
          EVENT_NAME: juno-dev
          IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}
          GOERLI: apps/dummy-dev/overlays/dummy-dev-1/config.yml
          GOERLI2: apps/dummy-dev/overlays/dummy-dev-2/config.yml
          TESTNET: apps/dummy-dev/overlays/dummy-dev-3/config.yml
          MAINNET: apps/dummy-dev/overlays/dummy-dev-4/config.yml
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ToluwalopeAyo/update-image-test/dispatches \
          -d '{"event_type": "${{ env.EVENT_NAME }}", "client_payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "goerli2_config": "${{ env.GOERLI2 }}", "testnet_config": "${{ env.TESTNET }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'

  deploy_to_staging:
    permissions: 
      id-token: write
      contents: write
    needs: [docker_build_and_publish]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    steps:
      - name: Repository Dispatch Dev
        env:
          EVENT_NAME: juno-dev
          IMAGE_TAG: ${{ github.event.inputs.tag }}
          GOERLI: apps/dummy-dev/overlays/dummy-dev-1/config.yml
          GOERLI2: apps/juno-dev/overlays/dev-goerli-2/config.yaml
          TESTNET: apps/dummy-dev/overlays/dummy-dev-3/config.yml
          MAINNET: apps/dummy-dev/overlays/dummy-dev-4/config.yml
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ToluwalopeAyo/update-image-test/dispatches \
          -d '{"event_type": "${{ env.EVENT_NAME }}", "client-payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "goerli2_config": "${{ env.GOERLI2 }}", "testnet_config": "${{ env.TESTNET }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'

  deploy_to_production:
    permissions: 
      id-token: write
      contents: write
    needs: [docker_build_and_publish, deploy_to_staging ]
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
      - name: Repository Dispatch Dev
        env:
          EVENT_NAME: juno-dev
          IMAGE_TAG: ${{ github.event.inputs.tag }}
          GOERLI: apps/juno-dev/overlays/dev-goerli-1/config.yaml
          GOERLI2: apps/juno-dev/overlays/dev-goerli-2/config.yaml
          TESTNET: apps/juno-dev/overlays/dev-integration/config.yaml
          MAINNET: apps/juno-dev/overlays/dev-mainnet/config.yaml
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ToluwalopeAyo/update-image-test/dispatches \
          -d '{"event_type": "${{ env.EVENT_NAME }}", "client-payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "goerli2_config": "${{ env.GOERLI2 }}", "testnet_config": "${{ env.TESTNET }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'
