name: Repository Dispatch Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Docker Image Tag to be deployed

env: 
  EVENT_NAME: dispatch
  GOERLI: apps/dummy-dev/overlays/dummy-dev-1/config.yml
  GOERLI2: apps/dummy-dev/overlays/dummy-dev-2/config.yml
  TESTNET:  apps/dummy-dev/overlays/dummy-dev-3/config.yml
  MAINNET: apps/dummy-dev/overlays/dummy-dev-4/config.yml
  
permissions:
  id-token: write
  contents: write

jobs:
  dispatch_test:
    runs-on: ubuntu-latest

    steps:          
      - name: Repo dispatch test
        env:
          IMAGE_TAG: ${{ github.event.inputs.tag }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ToluwalopeAyo/update-image-test/dispatches \
          -d '{"event_type": "${{ env.EVENT_NAME }}", "client_payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "goerli2_config": "${{ env.GOERLI2 }}", "testnet_config": "${{ env.TESTNET }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'

