name: Dispatch Render Juno Staging

on:
    workflow_dispatch:
      inputs:
        tag:
          description: Image tag 
          required: true

permissions:
  id-token: write
  contents: write

jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker pull, tag and push
        env:
          IMAGE_TAG: ${{ github.event.inputs.tag }}
        run: |
          docker pull tolulopeayo/hng-api:1
          docker tag tolulopeayo/hng-api:1 tolulopeayo/hnggg-apii:${{ env.IMAGE_TAG }}
          docker push tolulopeayo/hnggg-apii:${{ env.IMAGE_TAG }}

      